### ISSUE TITLE
context deadline exceeded error

### ISSUE THREAD

**Issue by mfertakos** [gnames/gnfinder#124]
Hello! I am working on extracting species names from several pdf files in Windows without Homebrew and WSL. A few of the files are 100+ pages long (100KB), and when I try to run in the cmd prompt:

gnfinder -u 2022_Sylvan_Nursery.pdf > nursery_pdf_species.csv

I get the vague error 'context deadline exceeded'. I know this usually occurs when a given action was not completed in an expected timeframe but I'm not sure how to resolve it within this package.

This process is working as expected for my shorter pdf files. Please let me know if you need more information, as I am new to this kind of work. Thanks in advance.

**Comment by dimus** [comment]
Hello @mfertakos, sorry for late reply, I had been enjoying my vation too much. GNparser depends on [Apache Tika](https://tika.apache.org/) service for tranforming PDFs into UTF8-encoded texts. Sometimes Tika is not able to finish this transformation because of the size of the document or its internal complexity or an inability for Tika to understand the file encoding.

You still can find names in documents that return `contexxt deadline exeeded` error, if you convert them to plain UTF-8 text youself using Acrobart reader, or other suitable program and then running:

```bash
gnfinder -u -U your_utf8_file.txt
```
The `-U` flag tells `gnfinder` to trust that the file is a UTF-8 text. In this case it does not send the content of the file to a remote Tika service and does everything locally.
