### ISSUE TITLE
Trailing dash after entity prevents recognition of full name

### ISSUE THREAD

**Issue by jasperfunksmit** [gnames/gnfinder#138]
When i feed the following text into GNFinder: ` Ardea alba-` the returned name is: **Ardea**. It should however return **Ardea alba**. 
If i remove the trailing dash the name **Ardea Alba** is returned correctly.
Any idea why this happens?

**Comment by dimus** [comment]
A dash in the end of the line usually means that the word with the dash is not complete and continues on the next line. Also, there are no scientific names that would end on a dash character. Because of these two known facts your example creates an 'unfinished' token. Most other additional characters , like commas, periods, quotes etc do not prevent a name to be recognized.

I guess we can treat the very last dash in a text differently, but I would suspect that in the real world scenarios it would be an extremely rare case to happen. Can you tell more about your practical use case, to see if it makes sense to implement such a fix?

**Comment by jasperfunksmit** [comment]
Thank you very much for answering! 

The original text is in German and lists animals depicted on an image. The dash character indicates it is part or a list.

Below the raw text I send to gnfinder:

`Obere Ecke rechts außen: "No. 54"; oben mittig: "Birds of Australia", rechts daneben: "Plate 106"; linke untere Ecke unten Zeichnung: "G. M. 61.".- Zeichnung selbst zeigt mehrere Vertreter verschiedener Vogelfamilien, jede mit einer Nummer versehen (von oben nach unten, links nach rechts): Nr. 512 Silberreiher (Ardea alba).- Nr. 519 Rotrückenreiher (Nycticorax caledonicus).- Nr. 509 Weißwangenreiher (Egretta novaehollandiae).- Nr. 504 Brolgakranich (Grus rubicunde).- Nr. 505 Gelbschnabellöffler (Platalea flavipes).- Nr. 521 Schwarzdommel (Ixobrychus flavicollis).- Nr. 508 Weißhalsreiher (Ardea pacifica).- Nr. 516 Riffreiher (Egretta sacra).- Nr. 520 Australische Rohrdommel (Botaurus poiciloptilus).- Nr. 511 unbekannt.- Nr. 501 Stachelibis (Threskiornis spinicollis).- Nr. 502 Australischer Ibis (Threskiornis molucca).- Nr. 538 Südsee-Sumpfhuhn (Porzana tabuensis).- Nr. 533 Krickralle (Rallus pectoralis).- Nr. 528 Rotfuß-Pfuhlhuhn (Gallinuia ventralis).- Nr. 525 unbekannt.- Nr. 529 unbekannt.- Nr. 530 Bläßhuhn (Fulica atra).- Nr. 535 Flusssumpfhuhn (Porzana fluminea).- Nr. 536 Zwergsumpfhuhn (Porzana pusilla).- Nr. 532 Buff-banded Rail (Gallirallus philippensis).`

**Comment by dimus** [comment]
@git-arbitrarysystems, thank you for the explanation. I think your particular text illustrates a gnfinder bug. It should be able to recognize names in parentheses. I'll try to fix this.
