### ISSUE TITLE
As a curator I would like finder to hit `       Alkonia tiquanus sp. nov.`

### ISSUE THREAD

**Issue by mjy** [gnames/gnfinder#141]
Using gem 'biodiversity', github: 'GlobalNamesArchitecture/biodiversity', branch: 'pipe_approach' # '~> 5.1', '>= 5.1.1' the following block of text returns no found names ((nor does the web-version find it):

```

                                           Alkonia tiquanus sp. nov.
                                        (Figs 1962-1968; Hab.  292)

Female (holotype): length, including ovipositor, 1.18mm; excluding ovipositor, 1.15mm (CPD).
    Head mainly black; vertex generally with a dull, metallic dark green sheen with coppery
```

**Comment by dimus** [comment]
I think the idea here is to have an option to detect names which are not registered in gnverifier database yet, but do contain an annotation like 'sp. nov.' and such. 
I would say that by default it should be off, because it would generate false positives, but it should be available as an option in cases when the Users knows what they are doing

**Comment by dimus** [comment]
part of #143
