### ISSUE TITLE
Salmonella not recognized 

### ISSUE THREAD

**Issue by serendipity-zhang** [gnames/gnfinder#147]

**Comment by dimus** [comment]
Salmonella is considered to be an ambiguous word, it might be used as a non biological name. Because of that it does not show in search by default. Such words would require a known specific epithet next to them. However when using '-A' flag it will be returned as a name:

```bash
00:39:58 ❯ echo "Salmonella" |gnfinder -A
Index,Verbatim,Name,Start,End,OddsLog10,Cardinality,AnnotNomenType,WordsBefore,WordsAfter
0,Salmonella,Salmonella,0,10,0.82,1,NO_ANNOT,,
```
The same can be achieved via Web GUI using Advanced options:

![image](https://github.com/gnames/gnfinder/assets/12124/b2b55f04-54a4-4c67-a318-2b257d3edb4c)

**Comment by dimus** [comment]
Another question is why `Salmonella` got into `ambiguous words`. I honestly cannot recall the reason, I'll look when it was added there, and may be it can be removed from that list.

**Comment by dimus** [comment]
Color: "Salmonella" can be used to describe a shade of pink or orange that is similar to the color of salmon fish flesh. For example, you might hear someone say, "The walls in the living room are painted in a salmonella color."

Design or Aesthetics: In the context of design or aesthetics, "Salmonella" can refer to a particular style or pattern that incorporates the color and texture associated with salmon. This use is less common but can be found in discussions related to fashion, interior design, or art.

I suspect 'salmon-like' use is rare enough, I think I can remove it from the 'ambiguous words'. It will be in effect when the next version is out.
