### ISSUE TITLE
any advice on taxonomic hunspell dictionaries?

### ISSUE THREAD

**Issue by sckott** [gnames/gnfinder#52]
via #51 -  didn't want to derail the conversation in #51 :

Wanted to mention: I'm interested in dictionaries in general - been tinkering with hunspell dictionaries https://github.com/ropenscilabs/taxdictionaries thinking maybe "spell checking" taxonomic names might be a useful/fast way to check names against known sets/rules locally - but this may be a bad idea, not sure yet. i went down the hunspell path because we have nice R bindings to the hunspell library. 

Any advice/learnings from gnfinder dictionaries?

**Comment by dimus** [comment]
gnfinder dictionaries have the following idea:

1. I got uninomial and n-nomial names from more or less curated sources taken from https://index.globalnames.org
2. Made uninomial word dictionary, species/infraspecies word dictionary
3. Got all genera from IRMNG, and set intersection of them with uinomials, saved the intersection as genus words
4. Got 1000 most popular words in each popular european language and made intersection between uninomial, genus, species words, saved results as grey dictionaries
5. Found all known canonical forms for grey generic words and saved them.
6. Started to look at name-finding results and weed out words that are not scientific like strand, environment, agricultural etc.

since then it is mostly eyeballing results, finding wrong things, and listening for feedback from others.

When I update https://index.globalnames.org I rebuld dictionaries as well using https://github.com/gnames/gnfinder-dict (a messy project, that I consider internal)

@sckott you might be curious about https://github.com/gnames/gnfinder-dict/tree/master/data files.

**Comment by dimus** [comment]
@sckott you might also be interested in https://github.com/gnames/gnverify
as well as the graphql apI it uses

https://github.com/gnames/gnverify/blob/master/src/verif/query.graphql

the endpoint for it is

http://index.globalnames.org/api/graphql

**Comment by sckott** [comment]
thanks very much @dimus  this is helpful 

i'm not working on this topic right now, but this is really helpful when I dig back into this. feel free to close this

hadn't seen gnverify - looks neat. 

looks like http://index.globalnames.org/api/graphql is down, maybe just temporary?

**Comment by dimus** [comment]
> looks like http://index.globalnames.org/api/graphql is down, maybe just temporary?

It is working, just no human readable output. Human-readable interface is here: 
https://bit.ly/2AZJngf

**Comment by dimus** [comment]
here is the query I use for gnverify:
https://github.com/gnames/gnverify/blob/master/src/verif/query.graphql

**Comment by sckott** [comment]
thanks!
